# Generated by Django 3.2.3 on 2022-01-31 18:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_user_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('DISPENSARY', 'Dispensary'), ('PROCESSOR', 'Processor'), ('GROWER', 'Grower'), ('TRANSPORT', 'Transport'), ('LAB', 'Lab'), ('OTHER', 'Other')], default='OTHER', max_length=25),
        ),
    ]
