# Generated by Django 3.2.3 on 2022-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_nickname',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
