# Generated by Django 3.2.3 on 2022-01-31 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_license_license_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=254)),
                ('location_type', models.CharField(choices=[('DISPENSARY', 'Dispensary'), ('PROCESSOR', 'Processor'), ('GROWER', 'Grower'), ('TRANSPORT', 'Transport'), ('LAB', 'Lab'), ('OTHER', 'Other')], max_length=100)),
                ('license_number', models.CharField(max_length=12, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='omma_license_number',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.company'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
