# Generated by Django 3.2.3 on 2022-01-31 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20220131_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_dba',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
